4-module.
js-tasks-ru/jsbasic-20230116-2_sanyches1978 pull request #5
Opened 2023-02-02 17:20 UTC by Alexandr-Ananev

implemented functions:  makeFriendsList, makeDiagonalRed, highlight.

2023-02-02 17:21 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-02-03 11:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-02-03 11:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-02-03 11:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-02-03 13:50 UTC, SinimaWath requested changes

2023-02-03 13:50 UTC, SinimaWath commented on 4-module/1-task/index.js
> +  document.body.insertAdjacentHTML('beforeend', '<ul></ul>');
По условию задачи, не надо вставлять в body, а просто вернуть ul

2023-02-03 13:50 UTC, SinimaWath commented on 4-module/2-task/index.js
> +  mark: for( let row = 0; row < rows.length; row++ ) {
Это считается антипаттерном и никогда не используется.


Задачу нужно переписать на один цикл: так как у диагонали cell === row

2023-02-03 13:50 UTC, SinimaWath commented on 5-module/2-task/index.js
> +    elem.hidden == false ? hide() : show();
можно упростить до: `elem.hidden = !elem.hidden`

2023-02-03 21:27 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-02-04 19:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-02-04 19:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-02-05 11:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-02-05 12:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-02-06 14:33 UTC, SinimaWath approved these changes

2023-02-06 14:34 UTC, merged